/**
* Descriptions for Agents
*/

module.exports = {
  id: 'Unique ID generated by Retsly to identify the agent.',
  mlsAgentID: 'A specific realtor\'s MLS ID number.',
  firstName: 'The first name of the listing agent.',
  lastName: 'The last name of the listing agent.',
  middleName: 'The middle name of the listing agent.',
  fullName: 'The full name of the listing agent.',
  title: 'The title of the listing agent, i.e. Mr., Mrs., Ms., Dr., etc.',
  cellPhone: 'The cell phone number of the listing agent.',
  homePhone: 'The home phone number of the listing agent.',
  office: 'An ID used by Retsly to reference the office associated with the agent.',
  mlsOfficeID: 'A specific office\'s MLS ID number associated with the agent.',
  officePhone: 'The office phone number associated with the agent.',
  officeName: 'The office name associated with the agent.',
  status: 'The status of the agent\'s MLS account, i.e. active, inactive, under disciplinary action.',
  media: 'An array of media associated with the listing agent.',
  url: 'URL to find details for the specific agent.',
  lastModified: 'The date which the agent was last modified.'
};
