module.exports = {
  id: 'Unique ID to identify the assessment.',
  apn: 'Assessor Parcel Number, the unique identifier assigned by the tax authority.',
  fips: 'Five digit county code ID.',
  county: 'County name.',
  state: 'Two character state abbreviation.',
  censusTract: 'Geographic region used by the US Census Bureau.',
  taxID: 'Unique identifier assigned for taxation purposes (different from APN).',
  taxAmount: 'Total dollar amount of property tax.',
  taxYear: 'Calendar year corresponding to the tax amount. May be different from year b/c some counties do not reassess every year.',
  taxExemption: 'Type of tax exemption, if any.',
  year: 'Assessment year.',
  landValue: 'Assessed value of land.',
  improvementValue: 'Assessed value of improvements',
  totalValue: 'Total assessed value of land and improvements.',
  landUseGeneral: 'Two character land use code (example: "RR" for Residential, "AG" for Agricultural).',
  landUseCode: 'Five character code describing this parcel\'s land use type.',
  landUseDescription: 'Description that matches the land use code.',
  zoningCode: 'Municipality-specific zoning code indicates what part of the zoning or land use bylaw applies to this parcel.',
  zoningDescription: 'Short description of zoning code.',
  numberOfBuildings: 'Number of buildings.',
  lotSizeAcres: 'Size of the lot in acres.',
  lotSizeSquareFeet: 'Size of the lot in square feet.',
  lotSizeFrontage: 'Eidth of the lot at the street (or shore for properties with water access).',
  lotSizeDepth: 'Average depth of lot perpendicular to frontage.',
  lotSizeIrregular: 'Perimeter measurements for non-rectangular shaped lots.',
  lotTopography: 'Short description of lot topography.',
  building: 'Building details.',
  ownerName: 'Name of owner.',
  address: 'Object conatining address attributes.',
  legal: 'Legal details of the assessment.',
  coordinates: 'Latitude and longitude.'
}
