var mediaSchema = require('./media');
var geoSchema = require('./geo');
var descriptions = require('./listing-desc');
var addDescriptions = require('./utils').addDescriptions;

var listingSchema = {
  id: {type: 'string'},
  mlsListingID: {type: 'string'},
  address: {type: 'string'},
  unitNumber: {type: 'string'},
  streetName: {type: 'string'},
  streetNumber: {type: 'string'},
  city: {type: 'string'},
  state: {type: 'string'},
  county: {type: 'string'},
  country: {type: 'string'},
  zipCode: {type: 'string'},
  subdivision: {type: 'string'},
  coordinates: {type: 'array', subtype: 'number'},
  _geo: { type: 'object', subtype: geoSchema },
  listDate: {type: 'string', format: 'date-time'},
  lastModified: {type: 'string', format: 'date-time'},
  price: {type: 'number'},
  previousPrice: {type: 'number'},
  originalPrice: {type: 'number'},
  closePrice: {type: 'number'},
  buyerFinancing: {type: 'string'},
  contingency: {type: 'string'},
  disclosures: {type: 'array', subtype: 'string'},
  unitsInBuilding: {type: 'number'},
  cancelationDate: {type: 'string', format: 'date-time'},
  expirationDate: {type: 'string', format: 'date-time'},
  termsOfSale: {type: 'array', subtype: 'string'},
  dateListed: {type: 'string', format: 'date-time'},
  dateSold: {type: 'string', format: 'date-time'},
  statusChange: {type: 'string', format: 'date-time'},
  ownership: {type: 'string'},
  financialDataSource: {type: 'string'},
  yearBuilt: {type: 'number'},
  yearBuiltDetails: {type: 'string'},
  daysOnMarket: {type: 'number'},
  appliances: {type: 'array', subtype: 'string'},
  telephoneService: {type: 'array', subtype: 'string'},
  view: {type: 'array', subtype: 'string'},
  waterfront: {type: 'boolean'},
  waterSource: {type: 'array', subtype: 'string'},
  zoning: {type: 'string'},
  zoningDescription: {type: 'string'},
  acres: {type: 'number'},
  squareFootage: {type: 'number'},
  livingArea: {type: 'number'},
  aboveGradeFinishedArea: {type: 'number'},
  belowGradeFinishedArea: {type: 'number'},
  stories: {type: 'number'},
  storiesTotal: {type: 'number'},
  baths: {type: 'number'},
  halfBaths: {type: 'number'},
  bedrooms: {type: 'number'},
  roomsTotal: {type: 'number'},
  fireplaces: {type: 'number'},
  fireplaceFeatures: {type: 'array', subtype: 'string'},
  exteriorFeatures: {type: 'array', subtype: 'string'},
  newConstruction: {type: 'boolean'},
  homeWarranty: {type: 'boolean'},
  architecturalStyle: {type: 'array', subtype: 'string'},
  communityFeatures: {type: 'array', subtype: 'string'},
  patioAndPorchFeatures: {type: 'array', subtype: 'string'},
  lotFeatures: {type: 'array', subtype: 'string'},
  basement: {type: 'array', subtype: 'string'},
  otherStructures: {type: 'array', subtype: 'string'},
  petsAllowed: {type: 'array', subtype: 'string'},
  flooring: {type: 'array', subtype: 'string'},
  foundationDetails: {type: 'array', subtype: 'string'},
  frontageLength: {type: 'number'},
  gas: {type: 'array', subtype: 'string'},
  accessibilityFeatures: {type: 'array', subtype: 'string'},
  cooling: {type: 'array', subtype: 'string'},
  heating: {type: 'array', subtype: 'string'},
  parcelNumber: {type: 'string'},
  additionalParcels: {type: 'boolean'},
  occupantType: {type: 'string'},
  pool: {type: 'boolean'},
  poolFeatures: {type: 'array', subtype: 'string'},
  poolPrivate: {type: 'boolean'},
  possession: {type: 'array', subtype: 'string'},
  roadSurface: {type: 'array', subtype: 'string'},
  roof: {type: 'array', subtype: 'string'},
  constructionMaterials: {type: 'array', subtype: 'string'},
  sewer: {type: 'array', subtype: 'string'},
  garageSpaces: {type: 'number'},
  carportSpaces: {type: 'number'},
  openParking: {type: 'boolean'},
  attachedGarage: {type: 'boolean'},
  carport: {type: 'boolean'},
  laundry: {type: 'array', subtype: 'string'},
  type: {type: 'string'},
  subtype: { type: 'string' },
  publicRemarks: {type: 'string'},
  privateRemarks: {type: 'string'},
  media: { type: 'array', subtype: mediaSchema },
  agent: {type: 'string'},
  mlsAgentID: {type: 'string'},
  office: {type: 'string'},
  mlsOfficeID: {type: 'string'},
  status: { type: 'string' },
  contractStatusChangeDate: {type: 'string', format: 'date-time'},
  contingentDate: {type: 'string', format: 'date-time'},
  withdrawnDate: {type: 'string', format: 'date-time'},
  offMarketDate: {type: 'string', format: 'date-time'},
  purchaseContractDate: {type: 'string', format: 'date-time'},
  originalEntryTimestamp: {type: 'string', format: 'date-time'},
  taxAssessedValue: {type: 'number'},
  taxAnnual: {type: 'number'},
  taxYear: {type: 'number'},
  taxStatus: {type: 'array', subtype: 'string'},
  association: {type: 'boolean'},
  associationName: {type: 'string'},
  associationFee: {type: 'number'},
  associationFeeFrequency: {type: 'string'},
  url: {type: 'string'}
};

var ddMap = {
  mlsListingID: 'ListingId',
  unitNumber: 'UnitNumber',
  streetName: 'StreetName',
  streetNumber: 'StreetNumber',
  city: 'City',
  state: 'StateOrProvince',
  county: 'CountyOrParish',
  country: 'Country',
  zipCode: 'PostalCode',
  subdivision: 'SubdivisionName',
  _geo: '_coordinates',
  listDate: 'ListingContractDate',
  lastModified : 'ModificationTimestamp',
  price: 'ListPrice',
  previousPrice: 'PreviousListPrice',
  originalPrice: 'OriginalListPrice',
  closePrice: 'ClosePrice',
  buyerFinancing: 'BuyerFinancing',
  contingency: 'Contingency',
  disclosures: 'Disclosures',
  unitsInBuilding: 'NumberOfUnitsTotal',
  cancelationDate: 'CancelationDate',
  expirationDate: 'ExpirationDate',
  termsOfSale: 'ClosingTerms',
  dateListed: 'OnMarketDate',
  dateSold: 'CloseDate',
  statusChange: 'StatusChangeTimestamp',
  ownership: 'Ownership',
  financialDataSource: 'FinancialDataSource',
  yearBuilt: 'YearBuilt',
  yearBuiltDetails: 'YearBuiltDetails',
  daysOnMarket: 'DaysOnMarket',
  appliances: 'Appliances',
  telephoneService: 'Telephone',
  view: 'View',
  waterfront: 'WaterfrontYN',
  waterSource: 'WaterSource',
  zoning: 'Zoning',
  zoningDescription: 'ZoningDescription',
  acres: 'LotSizeAcres',
  squareFootage: 'LotSizeSquareFeet',
  livingArea: 'LivingArea',
  aboveGradeFinishedArea: 'AboveGradeFinishedArea',
  belowGradeFinishedArea: 'BelowGradeFinishedArea',
  stories: 'Stories',
  storiesTotal: 'StoriesTotal',
  baths: 'BathroomsTotalInteger',
  halfBaths: 'BathroomsHalf',
  bedrooms: 'BedroomsTotal',
  roomsTotal: 'RoomsTotal',
  fireplaces: 'FireplacesTotal',
  fireplaceFeatures: 'FireplaceFeatures',
  exteriorFeatures: 'ExteriorFeatures',

  newConstruction: 'NewConstructionYN',
  homeWarranty: 'HomeWarrantyYN',
  architecturalStyle: 'ArchitecturalStyle',
  communityFeatures: 'CommunityFeatures',
  patioAndPorchFeatures: 'PatioAndPorchFeatures',
  lotFeatures: 'LotFeatures',
  basement: 'Basement',
  otherStructures: 'OtherStructures',
  petsAllowed: 'PetsAllowed',

  flooring: 'Flooring',
  foundationDetails: 'FoundationDetails',
  frontageLength: 'FrontageLength',
  gas: 'Gas',
  accessibilityFeatures: 'AccessibilityFeatures',
  cooling: 'Cooling',
  heating: 'Heating',
  parcelNumber: 'ParcelNumber',
  additionalParcels: 'AdditionalParcelsYN',
  occupantType: 'OccupantType',
  pool: 'PoolPrivateYN',
  poolFeatures: 'PoolFeatures',
  poolPrivate: 'PoolPrivateYN',
  possession: 'Possession',
  roadSurface: 'RoadSurfaceType',
  roof: 'Roof',
  constructionMaterials: 'ConstructionMaterials',
  sewer: 'Sewer',
  garageSpaces: 'GarageSpaces',
  carportSpaces: 'CarportSpaces',
  openParking: 'OpenParkingYN',
  attachedGarage: 'AttachedGarageYN',
  carport: 'CarportYN',
  laundry: 'LaundryFeatures',
  type: 'PropertyType',
  subtype: 'PropertySubType',
  publicRemarks: 'PublicRemarks',
  privateRemarks: 'PrivateRemarks',
  mlsAgentID: 'ListAgentKey',
  mlsOfficeID: 'ListOfficeKey',
  status: 'StandardStatus',
  contractStatusChangeDate: 'ContractStatusChangeDate',
  contingentDate: 'ContingentDate',
  withdrawnDate: 'WithdrawnDate',
  offMarketDate: 'OffMarketDate',
  purchaseContractDate: 'PurchaseContractDate',
  originalEntryTimestamp: 'OriginalEntryTimestamp',

  taxAssessedValue: 'TaxAssessedValue',
  taxAnnual: 'TaxAnnualAmount',
  taxYear: 'TaxYear',
  taxStatus: 'TaxStatusCurrent',

  association: 'AssociationYN',
  associationName: 'AssociationName',
  associationFee: 'AssociationFee',
  associationFeeFrequency: 'AssociationFeeFrequency'
};

module.exports = addDescriptions(listingSchema, descriptions, ddMap);
