/**
* Descriptions for Listings
*/

module.exports = {
  id: 'Unique ID generated by Retsly to identify the listing.',
  mlsListingID: 'The well known identifier for the listing.',
  address: 'Complete address for the listing property.',
  unitNumber: 'The unit number pertaining to apartments, etc.',
  streetName: 'The street name for the listing property.',
  streetNumber: 'The street number for the listing property.',
  city: 'The city which the listing property resides in.',
  state: 'The state which the listing property resides in.',

  county: 'The county with which the listing property resides in.',
  country: 'The country with which the listing property resides in.',
  zipCode: 'The postal code for the listing property.',
  subdivision: 'The name of the subdivision if the listing property has one.',
  _geo: 'The type and coordinates of the geospacial location of the listing property.',
  latitude: 'The latitude of the listing property\'s geospacial coordinates.',
  longitude: 'The longitude of the listing property\'s geospacial coordinates.',
  listDate: 'The date which the listing was posted.',
  lastModified: 'The date which the posted listing was last modified.',

  price: 'The current price of the listing property.',
  previousPrice: 'The last price of the listing property.',
  originalPrice: 'The first price of the listing property.',
  closePrice: 'The closing price of the listing property.',

  contingency: 'A list of contingencies that must be satisfied in order to complete the transaction.',
  disclosures: 'Legal or pertinent information that should be disclosed to potential buyer\'s agents',

  unitsInBuilding: 'The total number of units in the building if applicable.',

  cancelationDate: 'The cancelation date of the listing if applicable.',
  expirationDate: 'The expiration date of the listing if applicable.',
  termsOfSale: 'Additional details given regarding the terms of sale.',
  dateListed: 'The date that the property was first listed.',
  dateSold: 'The date that the property was sold.',
  statusChange: 'The date that the contractual status of the listing property was changed.',
  ownership: 'A text description of the manner in which title to a property is held.',

  financialDataSource: 'The source of the rental information, i.e. Accountant, Owner, etc.',

  importDate: 'The date which the listing was imported to the Retsly database.',
  yearBuilt: 'The year which the listing property was built.',
  yearBuiltDetails: 'A description of the details behing the year the structure was built.',
  daysOnMarket: 'The number of days the listing property has been posted on the market.',
  appliances: 'A list of the appliances that will be included in the sale/lease of the property.',
  telephoneService: 'A list of telephone-service related features of the property.',

  view: 'A description of the view as seen from the listed property.',
  waterfront: 'A boolean value indicating waterfront property.',
  waterSource: 'A list of the source(s) of water for the property.',
  zoning: 'Typically a shortcode indicating the zoning given for the lot to discern permissible land uses.',
  zoningDescription: 'A list of descriptions of the zoning of the property.',

  acres: 'The number of acres dedicated to the lot of the listed property.',
  squareFootage: 'The total lot size of the property given in square feet.',
  livingArea: 'The total livable area within the structure.',
  aboveGradeFinishedArea: 'The finished area within the structure that is at or above the surface of the ground.',
  belowGradeFinishedArea: 'The finished area within the structure that is below ground.',

  stories: 'The number of floors in the property being sold.',
  storiesTotal: 'The total number of floors in the building.',
  baths: 'The simple sum of the number of bathrooms. Two half baths and a full bathroom would be 3 total.',
  halfBaths: 'The number of rooms containing 2 of 4 elements constituting a bath, i.e. toilet, sink, bathtub, shower.',
  bedrooms: 'The total number of bedrooms in the dwelling.',
  roomsTotal: 'The total number of rooms within the listed property.',
  fireplaces: 'The total number of fireplaces within the listed property.',
  fireplaceFeatures: 'A list of features or description of the fireplace(s) included in the sale/lease.',
  exteriorFeatures: 'A list of features or description of the exterior of the property.',

  flooring: 'A list of the type(s) of flooring found within the property.',
  foundationDetails: 'A list of the type(s) of foundation on which the property sits.',
  frontageLength: 'Textual description of the length of the frontages for the listed property.',
  gas: 'A list of gas-service related features of the property.',
  accessibilityFeatures: 'A list or description of the accessibility features included in the sale/lease.',
  cooling: 'A list describing the cooling or air conditioning features of the property.',
  heating: 'A list describing the heating features of the property.',
  parcelNumber: 'A number used to uniquely identify a percel or lot. Can vary between county and entered without dashes or hyphens.',
  additionalParcels: 'A boolean indicating if more than one parcel or lot is included in the sale.',
  occupantType: 'A field that describes the type of occupant, i.e. Owner, Tenant, Vacant.',
  pool: 'A boolean indicating if the property has a privately owned pool that is included in the sale/lease.',
  poolFeatures: 'A list of features or description of the pool included in the sale/lease.',
  poolPrivate: 'A boolean indicating if the property has a privately owned pool that is included in the sale/lease.',
  possession: 'A list defining when the possession will occur.',
  roadSurface: 'A list of types of surface of the road to access the property.',
  roof: 'A list describing the type or style of roof.',
  constructionMaterials: 'A list of materials that were used in the construction of the property.',
  sewer: 'A list describing the sewer or septic features of the property.',

  garageSpaces: 'The number of spaces in the garage if applicable.',
  carportSpaces: 'The number of spaces in the carport if applicable.',
  openParking: 'A boolean indicating if there is open space parking.',
  laundry: 'List of features and locations where the laundry is located in the property.',
  
  type: 'A list of types of properties such as Residential, Lease, Income, Land, Mobile, etc.',
  subtype: 'A list of types of residential and residential lease properties, i.e. SFR, Condo',
  publicRemarks: 'Text remarks that may be displayed to the public.',
  privateRemarks: 'Remarks that may contain security or proprietary information that should be restricted from public view.',

  media: 'An object containing media information such as id, url and type.',
  agent: 'An ID used by Retsly to reference the agent associated with the listing.',
  mlsAgentID: 'A specific realtor\'s MLS ID number.',
  office: 'An ID used by Retsly to reference the office associated with the listing agent.',
  mlsOfficeID: 'A specific office\'s MLS ID number.',
  status: 'Local or regional MLS status.',

  taxAssessedValue: 'The property value as of the last assessment by the taxing authority.',
  taxAnnual: 'The annual property tax amount as of the last assessment made by the taxing authority.',
  taxYear: 'The year in which the last assessment of the property value/tax was made.',
  taxStatus: 'The current tax status of the mobile home in cases where the land or space is included in the sale.'
}
