var mediaSchema = require('./media');
var geoSchema = require('./geo');
var descriptions = require('./listing-desc');
var addDescriptions = require('./utils').addDescriptions;

var listingSchema = {
  id: {type: 'string'},
  mlsListingID: {type: 'string'},
  address: {type: 'string'},
  unitNumber: {type: 'string'},
  streetName: {type: 'string'},
  streetNumber: {type: 'string'},
  city: {type: 'string'},
  state: {type: 'string'},
  county: {type: 'string'},
  country: {type: 'string'},
  zipCode: {type: 'string'},
  subdivision: {type: 'string'},
  coordinates: {type: 'array', subtype: 'number'},
  _geo: {
    subtype: geoSchema,
    type: 'object'
  },
  listDate: {type: 'string', format: 'date-time'},
  lastModified: {type: 'string', format: 'date-time'},
  price: {type: 'number'},
  previousPrice: {type: 'number'},
  originalPrice: {type: 'number'},
  closePrice: {type: 'number'},
  contingency: {type: 'string'},
  disclosures: {type: 'array', subtype: 'string'},
  unitsInBuilding: {type: 'number'},
  cancelationDate: {type: 'string', format: 'date-time'},
  expirationDate: {type: 'string', format: 'date-time'},
  termsOfSale: {type: 'array', subtype: 'string'},
  dateListed: {type: 'string', format: 'date-time'},
  dateSold: {type: 'string', format: 'date-time'},
  statusChange: {type: 'string', format: 'date-time'},
  ownership: {type: 'string'},
  financialDataSource: {type: 'string'},
  yearBuilt: {type: 'number'},
  yearBuiltDetails: {type: 'string'},
  daysOnMarket: {type: 'number'},
  appliances: {type: 'array', subtype: 'string'},
  telephoneService: {type: 'array', subtype: 'string'},
  view: {type: 'array', subtype: 'string'},
  waterfront: {type: 'boolean'},
  waterSource: {type: 'array', subtype: 'string'},
  zoning: {type: 'string'},
  zoningDescription: {type: 'string'},
  acres: {type: 'number'},
  squareFootage: {type: 'number'},
  livingArea: {type: 'number'},
  aboveGradeFinishedArea: {type: 'number'},
  belowGradeFinishedArea: {type: 'number'},
  stories: {type: 'number'},
  storiesTotal: {type: 'number'},
  baths: {type: 'number'},
  halfBaths: {type: 'number'},
  bedrooms: {type: 'number'},
  roomsTotal: {type: 'number'},
  fireplaces: {type: 'number'},
  fireplaceFeatures: {type: 'array', subtype: 'string'},
  exteriorFeatures: {type: 'array', subtype: 'string'},
  flooring: {type: 'array', subtype: 'string'},
  foundationDetails: {type: 'array', subtype: 'string'},
  frontageLength: {type: 'number'},
  gas: {type: 'array', subtype: 'string'},
  accessibilityFeatures: {type: 'array', subtype: 'string'},
  cooling: {type: 'array', subtype: 'string'},
  heating: {type: 'array', subtype: 'string'},
  parcelNumber: {type: 'string'},
  additionalParcels: {type: 'boolean'},
  occupantType: {type: 'string'},
  pool: {type: 'boolean'},
  poolFeatures: {type: 'array', subtype: 'string'},
  poolPrivate: {type: 'boolean'},
  possession: {type: 'array', subtype: 'string'},
  roadSurface: {type: 'array', subtype: 'string'},
  roof: {type: 'string'},
  constructionMaterials: {type: 'array', subtype: 'string'},
  sewer: {type: 'array', subtype: 'string'},
  garageSpaces: {type: 'number'},
  carportSpaces: {type: 'number'},
  openParking: {type: 'boolean'},
  laundry: {type: 'array', subtype: 'string'},
  type: {type: 'string'},
  subtype: {
    type: 'string',
    enum: [
      "Apartment",
      "Boat Slip",
      "Single Family Residence",
      "Deeded Parking",
      "Cabin",
      "Condominium",
      "Duplex",
      "Farm",
      "Manufactured Home",
      "Mobile Home",
      "Own Your Own",
      "Quadruplex",
      "Stock Cooperative",
      "Townhouse",
      "Timeshare",
      "Triplex",
      "Manufactured on Land"
    ]
  },
  publicRemarks: {type: 'string'},
  privateRemarks: {type: 'string'},
  media: {
    type: 'array',
    subtype: mediaSchema
  },
  agent: {type: 'string'},
  mlsAgentID: {type: 'string'},
  office: {type: 'string'},
  mlsOfficeID: {type: 'string'},
  status: {
    type: 'string',
    enum: [
      "Active",
      "Active Under Contract",
      "Pending",
      "Hold",
      "Withdrawn",
      "Closed",
      "Expired",
      "Canceled",
      "Delete",
      "Incomplete",
      "Coming Soon"
    ]
  },
  contractStatusChangeDate: {type: 'string', format: 'date-time'},
  contingentDate: {type: 'string', format: 'date-time'},
  withdrawnDate: {type: 'string', format: 'date-time'},
  offMarketDate: {type: 'string', format: 'date-time'},
  purchaseContractDate: {type: 'string', format: 'date-time'},
  originalEntryTimestamp: {type: 'string', format: 'date-time'},
  taxAssessedValue: {type: 'number'},
  taxAnnual: {type: 'number'},
  taxYear: {type: 'number'},
  taxStatus: {type: 'array', subtype: 'string'},
  url: {type: 'string'},

};

module.exports = addDescriptions(listingSchema, descriptions);
