/**
* Descriptions for Media
*/

module.exports = {
  id: 'Unique ID generated by Retsly to identify the media.',
  mlsMediaID: 'A specific ID applied to the media by the MLS.',
  url: 'The URL associated to the media.',
  shortDescription: 'A short description about the media.',
  mimeType: 'The type of media being imported.',
  index: 'The numbered index given to the media when imported to the hosting server.'
};
