/**
* Descriptions for Office
*/

module.exports = {
  id: 'Unique ID generated by Retsly to identify the office.',
  mlsOfficeID: 'A specific office\'s MLS ID number.',
  type: 'The type of business conducted by the office, i.e. Association, MLS, Realtor Firm, etc.',
  address: 'The address associated to the office.',
  city: 'The city in which the office is located.',
  fax: 'The office\'s fax number.',
  email: 'The office\'s email address.',
  name: 'The name of the office.',
  phone: 'The phone number of the office.',
  state: 'The state that the office resides in.',
  zipCode: 'The zip code of the office.',
  status: 'The status of the office, i.e. active, inactive, under disciplinary action.',
};
