/**
* Descriptions for Openhouse
*/

module.exports = {
  id: 'Unique ID generated by Retsly to identify the open house.',
  mlsOpenhouseID: 'A unique identifier for this record from the immediate source.',
  listing: 'A generated Retsly listing ID or number that is associated with the open house.',
  mlsListingID: 'A unique MLS identifier for the listing associated with the open house.',
  agent: 'An ID used by Retsly to reference the agent associated with the open house.',
  mlsAgentKey: 'The MLS system identifier of the agent who is associated with the open house.',
  date: 'The date on which the open house will occur.',
  startTime: 'The start time of the open house.',
  endTime: 'The end time of the open house.',
  type: 'The type of open house, i.e. Public, Broker, Office, Private, etc.',
  remarks: 'Comments, instructions or information about the open house.',
  status: 'Status of the open house, i.e. Active, Cancelled, Ended, etc.',
  url: 'URL to find details for the specific openhouse.'
};
