module.exports = {
  id: 'Unique ID to identify the parcel.',
  apn: 'Assessor Parcel Number, the unique identifier assigned by the tax authority.',
  fips: 'Five digit county code ID.',
  county: 'County name.',
  state: 'Two character state abbreviation.',
  landUseGeneral: 'Two character land use code (example: "RR" for Residential, "AG" for Agricultural).',
  landUseCode: 'Five character code describing this parcel\'s land use type.',
  landUseDescription: 'Description that matches the land use code.',
  zoningCode: 'Municipality-specific zoning code indicates what part of the zoning or land use bylaw applies to this parcel.',
  zoningDescription: 'Short description of zoning code.',
  lotSizeAcres: 'Size of the lot in acres.',
  lotSizeSquareFeet: 'Size of the lot in square feet.',
  lotSizeFrontage: 'Distance in feet between the front of the building and the property boundary',
  lotSizeDepth: 'Average depth of lot perpendicular to frontage.',
  lotSizeIrregular: 'Perimeter measurements for non-rectangular shaped lots.',
  lotTopography: 'Short description of lot topography.',
  numberOfBuildings: 'Number of buildings included in the parcel.',
  building: 'Building data.',
  ownerName: 'Full name of the parcel owner.',
  address: 'Address attributes of the parcel.',
  legal: 'Legal details of the parcel.',
  coordinates: 'Latitude and longitude.'
};
