module.exports = {
  id: 'Unique ID to identify the transaction.',
  fips: 'Five digit county code ID.',
  county: 'County name.',
  state: 'Two character state abbreviation.',
  recordType: 'Two character code for record type.',
  recordingDate: 'The date this transaction was recorded.',
  recordingBookNumber: 'System book number of record.',
  recordingPageNumber: 'System page number of record.',
  documentTypeCode: 'Four character code for document type.',
  documentType: 'Short description of document type.',
  documentDate: 'Document creation date.',
  signatureDate: 'Date transaction was signed.',
  effectiveDate: 'Effective date transaction takes effect.',
  buyerVesting: 'Vesting process for buyer.',
  buyerMultiVesting: 'Flag for multi vesting.',
  partialInterestTransfer: 'Flag for partial interest transfers.',
  partialInterestTransferPercent: 'Percent of partial interest transfer.',
  salesPrice: 'Price of the sale.',
  cityTransferTax: 'City transfer tax.',
  countyTransferTax: 'County transfer tax.',
  stateTransferTax: 'County transfer tax.',
  totalTransferTax: 'Total transfer tax.',
  intraFamilyTransfer: 'Flag for intra family transfers.',
  transferTaxExempt: 'Flag for transfer tax exemption.',
  buyerName: 'Name of buyer.',
  sellerName: 'Name of seller.',
  borrowerVesting: 'Description of vesting process.',
  lenderName: 'Name of lender.',
  lenderType: 'The type of institution (bank, private lender, etc).',
  lenderID: 'Unique identifier for lender.',
  loanAmount: 'Amount of loan.',
  loanAmountDescription: 'Description of loan amount.',
  parcels: 'Parcel data.'
}
